import eslint from '@eslint/js'
import tseslint from 'typescript-eslint'
import prettier from 'eslint-config-prettier'

export default tseslint.config(
	eslint.configs.recommended,
	...tseslint.configs.recommended,
	prettier,
	{
		files: ['src/**/*.ts'],
		languageOptions: {
			ecmaVersion: 'latest',
			sourceType: 'module',
			globals: {
				window: 'readonly',
				document: 'readonly',
				navigator: 'readonly',
				console: 'readonly',
				setTimeout: 'readonly',
				clearTimeout: 'readonly',
				setInterval: 'readonly',
				clearInterval: 'readonly',
				fetch: 'readonly',
				Request: 'readonly',
				Response: 'readonly',
				URL: 'readonly',
				URLSearchParams: 'readonly',
				Blob: 'readonly',
				File: 'readonly',
				FileReader: 'readonly',
				FormData: 'readonly',
				Headers: 'readonly',
				AbortController: 'readonly',
				AbortSignal: 'readonly',
				crypto: 'readonly',
				performance: 'readonly',
				indexedDB: 'readonly',
				localStorage: 'readonly',
				sessionStorage: 'readonly',
				Worker: 'readonly',
				SharedWorker: 'readonly',
				MessageChannel: 'readonly',
				MessagePort: 'readonly',
				BroadcastChannel: 'readonly',
				AudioContext: 'readonly',
				OfflineAudioContext: 'readonly',
				WebGLRenderingContext: 'readonly',
				WebGL2RenderingContext: 'readonly',
				CanvasRenderingContext2D: 'readonly',
				HTMLCanvasElement: 'readonly',
				HTMLImageElement: 'readonly',
				HTMLVideoElement: 'readonly',
				HTMLAudioElement: 'readonly',
				HTMLIFrameElement: 'readonly',
				HTMLElement: 'readonly',
				Element: 'readonly',
				Node: 'readonly',
				NodeList: 'readonly',
				Event: 'readonly',
				CustomEvent: 'readonly',
				MouseEvent: 'readonly',
				KeyboardEvent: 'readonly',
				TouchEvent: 'readonly',
				MutationObserver: 'readonly',
				ResizeObserver: 'readonly',
				IntersectionObserver: 'readonly',
				RTCPeerConnection: 'readonly',
				MediaStream: 'readonly',
				MediaDevices: 'readonly',
				Intl: 'readonly',
				Promise: 'readonly',
				Map: 'readonly',
				Set: 'readonly',
				WeakMap: 'readonly',
				WeakSet: 'readonly',
				Symbol: 'readonly',
				Proxy: 'readonly',
				Reflect: 'readonly',
				ArrayBuffer: 'readonly',
				Uint8Array: 'readonly',
				Float32Array: 'readonly',
				DataView: 'readonly',
				TextEncoder: 'readonly',
				TextDecoder: 'readonly',
				atob: 'readonly',
				btoa: 'readonly',
				CompressionStream: 'readonly',
				CSS: 'readonly',
				CSSStyleDeclaration: 'readonly',
				getComputedStyle: 'readonly',
				matchMedia: 'readonly',
				requestAnimationFrame: 'readonly',
				cancelAnimationFrame: 'readonly',
				queueMicrotask: 'readonly',
				structuredClone: 'readonly',
			},
		},
		rules: {
			'@typescript-eslint/no-explicit-any': 'off',
			'@typescript-eslint/no-unused-vars': 'off',
			'@typescript-eslint/no-unused-expressions': 'off',
			'@typescript-eslint/ban-ts-comment': 'off',
			'@typescript-eslint/no-unsafe-function-type': 'off',
			'no-unused-vars': 'off',
			'no-empty': 'off',
			'no-useless-escape': 'off',
			'no-async-promise-executor': 'off',
			'no-prototype-builtins': 'off',
			'no-loss-of-precision': 'off',
			'no-constant-condition': 'off',
			'prefer-rest-params': 'off',
			'no-tabs': 'off',
			indent: 'off',
			semi: 'off',
			'max-len': 'off',
			'object-curly-spacing': 'off',
		},
	},
	{
		ignores: ['dist/**', 'node_modules/**', 'public/**', 'lib/**', 'bin/**', 'scripts/**'],
	}
)
