/**
 * Compile argus-web VM detection program to bytecode.
 *
 * Usage: npx tsx scripts/compile-vm.ts [--key <hex>] [--bucket <n>]
 *
 * Reads scripts/vm-src/main.ts (JS subset)
 * Compiles to BytecodeModule via compiler + acorn
 * Encodes to binary, XOR-scrambles with build-time key
 * Wraps with salt + stored_key into a packed blob (see src/vm/unpack.ts)
 * Writes src/vm/bytecode-modules.ts (generated, gitignored)
 *
 * --bucket is mainly for deterministic tests; production omits it so the
 * blob targets the current wall-clock bucket.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import * as crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { compile } from './compiler/index';
import { encode } from './compiler/encoder';
import { pack, SALT_LEN, KEY_LEN, BUCKET_MS } from '../src/vm/unpack';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const VM_SRC = path.join(ROOT, 'scripts/vm-src/main.ts');
const OUTPUT = path.join(ROOT, 'src/vm/bytecode-modules.ts');

function parseKey(): Uint8Array {
  const idx = process.argv.indexOf('--key');
  if (idx !== -1 && process.argv[idx + 1]) {
    return new Uint8Array(Buffer.from(process.argv[idx + 1], 'hex'));
  }
  return new Uint8Array(crypto.randomBytes(KEY_LEN));
}

function parseBucket(): number {
  const idx = process.argv.indexOf('--bucket');
  if (idx !== -1 && process.argv[idx + 1]) {
    return parseInt(process.argv[idx + 1], 10);
  }
  return Math.floor(Date.now() / BUCKET_MS);
}

async function main() {
  console.log('[compile-vm] Reading source...');
  const source = fs.readFileSync(VM_SRC, 'utf-8');

  const jsSource = source
    .replace(/\/\/\s*@ts-nocheck.*\n?/g, '')
    .replace(/^\s*\/\/.*$/gm, (line) => line);

  console.log('[compile-vm] Compiling...');
  const module = compile(jsSource);
  console.log(
    `[compile-vm] Compiled: ${module.code.length} instructions, ` +
      `${module.strings.length} strings, ${module.apiTable.length} API entries`,
  );

  console.log('[compile-vm] Encoding to binary...');
  const binary = encode(module);
  const bytes = new Uint8Array(binary);
  console.log(`[compile-vm] Binary size: ${bytes.length} bytes`);

  const realKey = parseKey();
  const salt = new Uint8Array(crypto.randomBytes(SALT_LEN));
  const bucket = parseBucket();
  console.log(
    `[compile-vm] Packing (bucket=${bucket}, salt=${Buffer.from(salt).toString('hex')})...`,
  );

  const blob = await pack(bytes, { realKey, salt, bucket });
  const b64 = Buffer.from(blob).toString('base64');
  console.log(`[compile-vm] Packed blob: ${blob.length} bytes, ${b64.length} base64 chars`);

  const output = `// Auto-generated by scripts/compile-vm.ts — DO NOT EDIT
// Generated: ${new Date().toISOString()}
// Bucket: ${bucket} (valid ±${3} buckets = ~7 days at 24h bucket size)

/** Packed VM bytecode (base64). Layout: [salt][scrambled][stored_key]. See src/vm/unpack.ts. */
export const VM_BYTECODE = '${b64}';
`;

  fs.writeFileSync(OUTPUT, output, 'utf-8');
  console.log(`[compile-vm] Written to ${path.relative(ROOT, OUTPUT)}`);
}

main().catch((err) => {
  console.error('[compile-vm] FAILED:', err);
  process.exit(1);
});
