/**
 * Compile argus-web VM detection program to bytecode.
 *
 * Usage: npx tsx scripts/compile-vm.ts [--key <hex>]
 *
 * Reads scripts/vm-src/main.ts (JS subset)
 * Compiles to BytecodeModule via compiler + acorn
 * Encodes to binary, XOR-scrambles with build-time key
 * Writes src/vm/bytecode-modules.ts (generated, gitignored)
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import * as crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { compile } from './compiler/index';
import { encode } from './compiler/encoder';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const VM_SRC = path.join(ROOT, 'scripts/vm-src/main.ts');
const OUTPUT = path.join(ROOT, 'src/vm/bytecode-modules.ts');

function parseKey(): Buffer {
  const idx = process.argv.indexOf('--key');
  if (idx !== -1 && process.argv[idx + 1]) {
    return Buffer.from(process.argv[idx + 1], 'hex');
  }
  return crypto.randomBytes(32);
}

function xorScramble(data: Uint8Array, key: Buffer): Uint8Array {
  const result = new Uint8Array(data.length);
  for (let i = 0; i < data.length; i++) {
    result[i] = data[i] ^ key[i % key.length];
  }
  return result;
}

function main() {
  console.log('[compile-vm] Reading source...');
  const source = fs.readFileSync(VM_SRC, 'utf-8');

  // Generate deploy secret first — it gets injected into the source before compilation
  // so the actual random value is embedded in the bytecode string pool, not the placeholder.
  const deploySecret = crypto.randomBytes(16).toString('hex');

  // Strip TypeScript-specific syntax and inject the deploy secret
  const jsSource = source
    .replace(/\/\/\s*@ts-nocheck.*\n?/g, '')
    .replace(/^\s*\/\/.*$/gm, (line) => line) // keep comments
    .replace("'__DEPLOY_SECRET__'", JSON.stringify(deploySecret)); // embed actual secret

  console.log('[compile-vm] Compiling...');
  const module = compile(jsSource);
  console.log(
    `[compile-vm] Compiled: ${module.code.length} instructions, ` +
      `${module.strings.length} strings, ${module.apiTable.length} API entries`,
  );

  console.log('[compile-vm] Encoding to binary...');
  const binary = encode(module);
  const bytes = new Uint8Array(binary);
  console.log(`[compile-vm] Binary size: ${bytes.length} bytes`);

  console.log('[compile-vm] XOR scrambling...');
  const key = parseKey();
  const scrambled = xorScramble(bytes, key);

  const b64 = Buffer.from(scrambled).toString('base64');
  const keyHex = key.toString('hex');

  const output = `// Auto-generated by scripts/compile-vm.ts — DO NOT EDIT
// Generated: ${new Date().toISOString()}

/** XOR-scrambled bytecode (base64) */
export const VM_BYTECODE = '${b64}';

/** XOR key (hex) */
export const VM_KEY = '${keyHex}';

/** Deploy-time secret for integrity hash */
export const DEPLOY_SECRET = '${deploySecret}';
`;

  fs.writeFileSync(OUTPUT, output, 'utf-8');
  console.log(`[compile-vm] Written to ${path.relative(ROOT, OUTPUT)}`);
  console.log(`[compile-vm] Deploy secret: ${deploySecret.slice(0, 8)}...`);
}

main();
